### ISSUE TITLE
It reported an error when I ran 'train.py' ,and I can't solve it

### ISSUE THREAD

**Issue by CiaranYoung** [avishkarsaha/translating-images-into-maps#15]
loading val data
Traceback (most recent call last):
  File "train.py", line 945, in <module>
    main()
  File "train.py", line 860, in main
    n_dec_layers=args.n_dec_layers,
  File "/home/csib/Y_C/translating-images-into-maps/src/model/network.py", line 1009, in __init__
    backbone_name=frontend, pretrained=pretrained
  File "/home/csib/Y_C/translating-images-into-maps/src/model/backbone_utils.py", line 90, in resnet_fpn_backbone
    pretrained=pretrained, norm_layer=misc_nn_ops.FrozenBatchNorm2d
  File "/home/csib/Y_C/translating-images-into-maps/src/model/resnet.py", line 841, in resnet50
    return _resnet("resnet50", Bottleneck, [3, 4, 6, 3], pretrained, progress, **kwargs)
  File "/home/csib/Y_C/translating-images-into-maps/src/model/resnet.py", line 793, in _resnet
    state_dict = load_state_dict_from_url(model_urls[arch], progress=progress)
  File "/home/csib/anaconda3/envs/bev37/lib/python3.7/site-packages/torch/hub.py", line 731, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/home/csib/anaconda3/envs/bev37/lib/python3.7/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/csib/anaconda3/envs/bev37/lib/python3.7/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

**Comment by CiaranYoung** [comment]
Thanks,I have solved it by re-downloading the pre-trained model

**Comment by CiaranYoung** [comment]
And it needed to delete the original model file which has been downloaded.
