### ISSUE TITLE
lmdb error - data.mdb missing

### ISSUE THREAD

**Issue by deepakduggirala** [avishkarsaha/translating-images-into-maps#20]
I downloaded the nuscenes_data from the google drive and upon running train.py, it ends in this error.

```
loading train data
Traceback (most recent call last):
  File "/N/projects/translating-images-into-maps/train.py", line 945, in <module>
    main()
  File "/N/projects/translating-images-into-maps/train.py", line 804, in main
    train_data = nuScenesMaps(
  File "/N/projects/translating-images-into-maps/src/data/dataloader.py", line 87, in __init__
    self.images_db = lmdb.open(
lmdb.Error: /N/projects/translating-images-into-maps/nuscenes_data/lmdb/samples/CAM_FRONT: No such file or directory
```

In the Google drive and subsequently in the downloaded files, data.mbd is missing
```
ls -latr /N/projects/translating-images-into-maps/nuscenes_data/lmdb/samples/CAM_FRONT
total 24
-rw-rw-r--@ 1 deepakduggirala  staff  8192 Jun 13 12:02 lock.mdb
-rw-rw-r--@ 1 deepakduggirala  staff   162 Jun 13 12:02 .data.mdb.icloud
drwxr-xr-x@ 4 deepakduggirala  staff   128 Nov 21 00:23 .
drwxr-xr-x@ 4 deepakduggirala  staff   128 Nov 21 00:24 ..
```

<img width="1134" alt="image" src="https://user-images.githubusercontent.com/1618149/203402177-85b2d71c-8c3c-45e4-a1ab-40ecbba0a9f5.png">

Could you please re-upload the data.mdb file to google drive?

**Comment by avishkarsaha** [comment]
Hi, I have now provided a new link to the data on iCloud.
