### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by wang-TJ-20** [avishkarsaha/translating-images-into-maps#8]
Traceback (most recent call last):
  File "D:/BEV/translating-images-into-maps-main/translating-images-into-maps-main/train.py", line 951, in <module>
    main()
  File "D:/BEV/translating-images-into-maps-main/translating-images-into-maps-main/train.py", line 938, in main
    train(args, train_loader, model, optimizer, epoch)
  File "D:/BEV/translating-images-into-maps-main/translating-images-into-maps-main/train.py", line 53, in train
    for i, ((image, calib, grid2d), (cls_map, vis_mask)) in enumerate(dataloader):
  File "E:\ananconda\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "E:\ananconda\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "E:\ananconda\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
    w.start()
  File "E:\ananconda\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "E:\ananconda\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "E:\ananconda\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "E:\ananconda\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "E:\ananconda\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'Environment' object
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\ananconda\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "E:\ananconda\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

how to slove this problem

**Comment by wang-TJ-20** [comment]
@wang-TJ-20 
when in Windows, you should set numworks = 0

**Comment by avishkarsaha** [comment]
I will release the dataloader that works without lmdb's in a few weeks.

**Comment by gongyan1** [comment]
@avishkarsaha Thank you for your excellent achievements, which have greatly promoted the development of BEV field. Do you plan to publish the dataloader that does not need LMDB recently? Thank you for your time.
